"""Render the Samba include files.

The renderer REFUSES anything that is not provably safe; it never escapes. Every value
is re-checked here even though callers validate first (defense in depth): a value that
reaches smb.conf can never contain a newline, a section bracket at line start, a
substitution (%), or a line continuation (backslash).
"""

from __future__ import annotations

import ipaddress
import re
from collections.abc import Iterable

from ssm import validators as v
from ssm.models import ACCESS_VALUES, ShareSpec

SMB_GROUP = "smbusers"
HEADER = "# Generated by smb-share-manager. Do not edit: this file is rewritten on every change.\n"
SERVER_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9-]{0,14}", re.ASCII)


class RenderError(ValueError):
    """Input that must not be written into smb.conf."""


def _check(fn: object, value: object) -> str:
    try:
        return fn(value)  # type: ignore[operator, no-any-return]
    except (v.ValidationError, TypeError) as e:
        raise RenderError(str(e)) from e


def _line(key: str, value: str) -> str:
    # Last-line guard: whatever happened above, a rendered line is a single safe line.
    if v.has_control_chars(value) or "%" in value or value.endswith("\\"):
        raise RenderError(f"unsafe value for {key}")
    return f"\t{key} = {value}"


def _share_lines(s: ShareSpec) -> list[str]:
    name = _check(v.validate_share_name, s.name)
    path = _check(v.validate_path_text, s.path)
    comment = _check(v.validate_comment, s.comment)
    if not isinstance(s.members, dict):
        raise RenderError("members must be a mapping")
    readers: list[str] = []
    writers: list[str] = []
    for user, access in sorted(s.members.items()):
        _check(v.validate_username, user)
        if access not in ACCESS_VALUES:
            raise RenderError("member access must be 'ro' or 'rw'")
        (writers if access == "rw" else readers).append(user)
    if s.all_users is not None and s.all_users not in ACCESS_VALUES:
        raise RenderError("all-users access must be 'ro', 'rw' or None")

    valid: list[str] = []
    write: list[str] = []
    if s.all_users is not None:
        valid.append("@" + SMB_GROUP)
        if s.all_users == "rw":
            write.append("@" + SMB_GROUP)
    valid += sorted(readers + writers)
    if s.all_users != "rw":
        write += writers

    lines = [f"[{name}]", _line("path", path)]
    if comment:
        lines.append(_line("comment", comment))
    if not valid:
        # Requirement 3: a share nobody may use must be unreachable. Validation refuses
        # this earlier; this is the backstop. 'nobody' has no Samba password entry.
        lines += [_line("available", "no"), _line("valid users", "nobody")]
    else:
        lines.append(_line("valid users", " ".join(valid)))
        if write:
            lines.append(_line("write list", " ".join(write)))
    lines += [
        _line("read only", "yes"),
        _line("guest ok", "no"),
        _line("browseable", "yes"),
        _line("force group", SMB_GROUP),
        _line("create mask", "0664"),
        _line("directory mask", "2775"),
    ]
    if s.no_unix_perms:
        # exFAT/vfat/ntfs: no xattrs and no unix permissions, so no named-stream module
        # can work (streams_xattr and streams_depot both need xattrs). Keep vfs_fruit
        # loaded (macOS negotiates its extensions per connection) with the resource fork
        # stored as an AppleDouble file; Finder stores other metadata in ._ files itself.
        lines += [
            _line("vfs objects", "fruit"),
            _line("fruit:metadata", "netatalk"),
            _line("fruit:resource", "file"),
            _line("ea support", "no"),
            _line("store dos attributes", "no"),
            _line("map archive", "no"),
            _line("map hidden", "no"),
            _line("map system", "no"),
            _line("map readonly", "no"),
        ]
    else:
        lines.append(_line("vfs objects", "fruit streams_xattr"))
    return lines


def render_shares(shares: Iterable[ShareSpec]) -> str:
    specs = list(shares)
    seen: set[str] = set()
    for s in specs:
        if not isinstance(s.name, str):
            raise RenderError("share name must be text")
        key = s.name.lower()
        if key in seen:
            raise RenderError(f"duplicate share name {s.name!r}")
        seen.add(key)
    out = [HEADER.rstrip("\n")]
    for s in sorted(specs, key=lambda x: x.name.lower()):
        out.append("")
        out += _share_lines(s)
    return "\n".join(out) + "\n"


def _check_host(entry: str) -> str:
    if not isinstance(entry, str) or v.has_control_chars(entry) or entry != entry.strip():
        raise RenderError("invalid hosts allow entry")
    try:
        return str(ipaddress.ip_network(entry, strict=False))
    except ValueError as e:
        raise RenderError(f"hosts allow entry {entry!r} is not an IP address or network") from e


def render_globals(hosts_allow: list[str], server_name: str, enable_nmbd: bool) -> str:
    if not isinstance(server_name, str) or not SERVER_NAME_RE.fullmatch(server_name):
        raise RenderError("server name must be 1-15 letters, digits or '-'")
    lines = [HEADER.rstrip("\n"), "[global]", _line("netbios name", server_name)]
    lines.append(_line("disable netbios", "no" if enable_nmbd else "yes"))
    if hosts_allow:
        nets = [_check_host(h) for h in hosts_allow]
        allowed = ["127.0.0.1", "::1"] + [n for n in nets if n not in ("127.0.0.1/32", "::1/128")]
        lines.append(_line("hosts allow", " ".join(allowed)))
        lines.append(_line("hosts deny", "0.0.0.0/0 ::/0"))
    return "\n".join(lines) + "\n"


_SECTION = re.compile(r"^\s*\[([^\]]*)\]\s*$")


def parse_sections(text: str) -> dict[str, dict[str, str]]:
    """Parse testparm-style output (or our own) into {section: {param: value}}."""
    out: dict[str, dict[str, str]] = {}
    current: dict[str, str] | None = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ";")):
            continue
        m = _SECTION.match(raw)
        if m:
            current = out.setdefault(m.group(1), {})
            continue
        if current is not None and "=" in line:
            k, _, val = line.partition("=")
            current[k.strip().lower()] = val.strip()
    return out
